apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-portfolio-deployment-01
  labels:
    app: stock-portfolio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stock-portfolio
  template:
    metadata:
      labels:
        app: stock-portfolio
    spec:
      containers:
      - name: stock-portfolio
        image: tkalden01/stock-portfolio:latest
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
      imagePullSecrets:
      - name: regcred