# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: stock-portfolio
spec:
  selector:
    app: stock-portfolio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer