apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-portfolio
  labels:
    app: stock-portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stock-portfolio
  template:
    metadata:
      labels:
        app: stock-portfolio
    spec:
      containers:
      - name: stock-portfolio
        image: stock-portfolio:latest
        imagePullPolicy: Never  # For local development
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          value: "main.py"
        - name: FLASK_ENV
          value: "production"
        - name: FLASK_DEBUG
          value: "False"
        - name: PORT
          value: "5000"
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        - name: PYTHONPATH
          value: "/app"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: stock-portfolio-secret
              key: secret-key
              optional: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
